### ISSUE TITLE
dnscrypt-proxy-openrc does not create user needed to run service

### ISSUE THREAD

**Issue by somenxavier** [artix-linux/packages-galaxy#2]
It needs to create user `dnscrypt`: manual intervention needed to create dnscrypt user (`useradd -r -s /usr/bin/nologin -g dnscrypt dnscrypt`). Groups dnscrypt is created. So from user perspective it is a bug

Please, fix package accordingly.
Thanks

**Comment by physkets** [comment]
If I have a user & group from the old 'dnscrypt-proxy', do I have to change anything to it? I ask because the service is currently crashing, and it looks like a 'dndcrypt' user related issue.

**Comment by physkets** [comment]
68abc0aa1787825cb242fb38cd1dc64ead29368b

**Comment by physkets** [comment]
https://github.com/artix-linux/packages-galaxy/commit/8f948682c1904642f0d2a386af9fa2749c34966c solves this
