### ISSUE TITLE
Calamares 3.2.0-3 doesn't run: it needs to be rebuilt against boost-libs 1.67

### ISSUE THREAD

**Issue by FredBezies** [artix-linux/packages-galaxy#6]
Hello.

Following your wiki to make a new installation ISO, I noticed on generated ISO that Calamares doesn't run.

When I try to launch it from terminal, I got an error related to a shared library version which cannot be found. As boost-libs was upgraded to version 1.67 in june 2018, you cannot run Calamares 3.2.0-3 built against boost-libs 1.66 :(

Boost-libs 1.67 on Archlinux ? June 8, 2018 -> https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/boost&id=d6a267587e2703ef17ef7a746f7827e7e84a1168

**Comment by alium** [comment]
will recompile over the next few minutes. Thanks for the message! please test after update! (calamares-3.2.0-3.1)

**Comment by FredBezies** [comment]
I will wait until it is available on mirrors, build a new ISO and report :)

**Comment by FredBezies** [comment]
Fixed! Thanks!
